---
abstract: 'update your git repository after release'
author:
  - 'Jerome Quelin'
build_requires:
  Dist::Zilla::File::InMemory: 0
  Dist::Zilla::Role::Releaser: 0
  Dist::Zilla::Tester: 0
  Exporter: 0
  File::Copy: 0
  File::Copy::Recursive: 0
  File::Find: 0
  File::Path: 2.07
  File::Which: 0
  File::pushd: 0
  Log::Dispatchouli: 0
  Module::Build: 0
  Test::DZil: 0
  Test::Fatal: 0.006
  Test::More: 0.88
configure_requires:
  Module::Build: 0.3601
  version: 0.80
  warnings: 0
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.120921'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Git
no_index:
  directory:
    - corpus
    - t
provides:
  Dist::Zilla::Plugin::Git:
    file: lib/Dist/Zilla/Plugin/Git.pm
    version: 2.015
  Dist::Zilla::Plugin::Git::Check:
    file: lib/Dist/Zilla/Plugin/Git/Check.pm
    version: 2.015
  Dist::Zilla::Plugin::Git::Commit:
    file: lib/Dist/Zilla/Plugin/Git/Commit.pm
    version: 2.015
  Dist::Zilla::Plugin::Git::CommitBuild:
    file: lib/Dist/Zilla/Plugin/Git/CommitBuild.pm
    version: 2.015
  Dist::Zilla::Plugin::Git::GatherDir:
    file: lib/Dist/Zilla/Plugin/Git/GatherDir.pm
    version: 2.015
  Dist::Zilla::Plugin::Git::Init:
    file: lib/Dist/Zilla/Plugin/Git/Init.pm
    version: 2.015
  Dist::Zilla::Plugin::Git::NextVersion:
    file: lib/Dist/Zilla/Plugin/Git/NextVersion.pm
    version: 2.015
  Dist::Zilla::Plugin::Git::Push:
    file: lib/Dist/Zilla/Plugin/Git/Push.pm
    version: 2.015
  Dist::Zilla::Plugin::Git::Tag:
    file: lib/Dist/Zilla/Plugin/Git/Tag.pm
    version: 2.015
  Dist::Zilla::PluginBundle::Git:
    file: lib/Dist/Zilla/PluginBundle/Git.pm
    version: 2.015
  Dist::Zilla::Role::Git::DirtyFiles:
    file: lib/Dist/Zilla/Role/Git/DirtyFiles.pm
    version: 2.015
  Dist::Zilla::Role::Git::Repo:
    file: lib/Dist/Zilla/Role/Git/Repo.pm
    version: 2.015
requires:
  Class::MOP: 0
  Cwd: 0
  DateTime: 0
  Dist::Zilla: 4
  Dist::Zilla::Plugin::GatherDir: 4.200016
  Dist::Zilla::Role::AfterBuild: 0
  Dist::Zilla::Role::AfterMint: 0
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::BeforeRelease: 0
  Dist::Zilla::Role::FilePruner: 0
  Dist::Zilla::Role::PluginBundle: 0
  Dist::Zilla::Role::VersionProvider: 0
  File::Spec: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::chdir: 0
  Git::Wrapper: 0.021
  IPC::Open3: 0
  IPC::System::Simple: 0
  List::AllUtils: 0
  List::Util: 0
  Moose: 0
  Moose::Autobox: 0
  Moose::Role: 0
  Moose::Util::TypeConstraints: 0
  MooseX::AttributeShortcuts: 0
  MooseX::Has::Sugar: 0
  MooseX::Types::Moose: 0
  MooseX::Types::Path::Class: 0
  Path::Class: 0.22
  Path::Class::Dir: 0
  String::Formatter: 0
  Try::Tiny: 0
  Version::Next: 0
  constant: 0
  namespace::autoclean: 0.09
  perl: 5.010
  strict: 0
  version: 0.80
  warnings: 0
resources:
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Git
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Git/
  repository: git://github.com/madsen/dist-zilla-plugin-git.git
  x_MailingList: http://www.listbox.com/subscribe/?list_id=139292
version: 2.015
x_Dist_Zilla:
  perl:
    version: 5.014002
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: MetaNoIndex
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: JQ/Git::NextVersion
      version: ~
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: JQ/GatherDir
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Test::Compile
      name: JQ/Test::Compile
      version: 2.002
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: JQ/PodCoverageTests
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: JQ/PodSyntaxTests
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: JQ/ReportVersions::Tiny
      version: 1.08
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: JQ/PruneCruft
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PruneFiles
      name: JQ/PruneFiles
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: JQ/ManifestSkip
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: JQ/AutoPrereqs
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: JQ/ExtraTests
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: JQ/NextRelease
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: JQ/PkgVersion
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: JQ/PodWeaver
      version: 3.101641
    -
      class: Dist::Zilla::Plugin::Prepender
      name: JQ/Prepender
      version: 1.112280
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: JQ/ExecDir
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: JQ/ShareDir
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: JQ/Bugtracker
      version: 1.111080
    -
      class: Dist::Zilla::Plugin::Homepage
      name: JQ/Homepage
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: JQ/Repository
      version: 0.18
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: JQ/MetaProvides::Package
      version: 1.14000002
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: JQ/MetaConfig
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::HelpWanted
      name: JQ/HelpWanted
      version: 0.2.1
    -
      class: Dist::Zilla::Plugin::License
      name: JQ/License
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Covenant
      name: JQ/Covenant
      version: 0.1.0
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: JQ/MetaYAML
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: JQ/MetaJSON
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Readme
      name: JQ/Readme
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: JQ/ReadmeAnyFromPod
      version: 0.120120
    -
      class: Dist::Zilla::Plugin::Manifest
      name: JQ/Manifest
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: JQ/CheckChangeLog
      version: 0.01
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: JQ/TestRelease
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: JQ/Git::Check
      version: ~
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: JQ/Git::Commit
      version: ~
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: JQ/Git::Tag
      version: ~
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: JQ/Git::Push
      version: ~
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: JQ/UploadToCPAN
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ModuleBuild::Custom
      name: ModuleBuild::Custom
      version: 4.16
    -
      class: Dist::Zilla::Plugin::FileFinder::ByName
      name: ':BuildPL'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: ConfirmRelease
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.300034
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: 4.300034
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 1
    version: 4.300034
x_author_pledge:
  version: 1
