---
abstract: 'update your git repository after release'
author:
  - 'Jerome Quelin'
build_requires:
  Module::Build: 0.35
configure_requires:
  Module::Build: 0.35
generated_by: 'Dist::Zilla version 1.093220'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Git
provides:
  Dist::Zilla::Plugin::Git:
    file: lib/Dist/Zilla/Plugin/Git.pm
    version: 1.093240
requires:
  Cwd: 0
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::BeforeRelease: 0
  English: 0
  ExtUtils::MakeMaker: 0
  File::Find: 0
  File::Spec::Functions: 0
  File::Temp: 0
  Git::Wrapper: 0
  IPC::Open3: 0
  Module::Build: 0
  Moose: 0
  MooseX::Has::Sugar: 0
  MooseX::Types::Moose: 0
  Symbol: 0
  Test::More: 0
  perl: 5.008
resources:
  MailingList: http://www.listbox.com/subscribe/?list_id=139292
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Git/
  repository: http://github.com/jquelin/dist-zilla-plugin-git
version: 1.093240
