---
abstract: 'update your git repository after release'
author:
  - 'Jerome Quelin'
build_requires:
  Carp: 0
  Dist::Zilla::Tester: 0
  English: 0
  File::Find: 0
  Module::Build: 0.3601
  Path::Class: 0
  Scalar::Util: 0
  Test::Exception: 0
  Test::More: 0.94
  version: 0
configure_requires:
  Module::Build: 0.3601
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.101900, CPAN::Meta::Converter version 2.101670'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Dist-Zilla-Plugin-Git
provides:
  Dist::Zilla::Plugin::Git:
    file: lib/Dist/Zilla/Plugin/Git.pm
    version: 1.102010
  Dist::Zilla::Plugin::Git::Check:
    file: lib/Dist/Zilla/Plugin/Git/Check.pm
    version: 1.102010
  Dist::Zilla::Plugin::Git::Commit:
    file: lib/Dist/Zilla/Plugin/Git/Commit.pm
    version: 1.102010
  Dist::Zilla::Plugin::Git::CommitBuild:
    file: lib/Dist/Zilla/Plugin/Git/CommitBuild.pm
    version: 1.102010
  Dist::Zilla::Plugin::Git::Init:
    file: lib/Dist/Zilla/Plugin/Git/Init.pm
    version: 1.102010
  Dist::Zilla::Plugin::Git::Push:
    file: lib/Dist/Zilla/Plugin/Git/Push.pm
    version: 1.102010
  Dist::Zilla::Plugin::Git::Tag:
    file: lib/Dist/Zilla/Plugin/Git/Tag.pm
    version: 1.102010
  Dist::Zilla::PluginBundle::Git:
    file: lib/Dist/Zilla/PluginBundle/Git.pm
    version: 1.102010
  Dist::Zilla::Role::Git::DirtyFiles:
    file: lib/Dist/Zilla/Role/Git/DirtyFiles.pm
    version: 1.102010
requires:
  Class::MOP: 0
  Cwd: 0
  DateTime: 0
  Dist::Zilla: 2.100880
  Dist::Zilla::Role::AfterBuild: 0
  Dist::Zilla::Role::AfterMint: 0
  Dist::Zilla::Role::AfterRelease: 0
  Dist::Zilla::Role::BeforeRelease: 0
  Dist::Zilla::Role::PluginBundle: 0
  File::Spec::Functions: 0
  File::Temp: 0
  File::chdir: 0
  Git::Wrapper: 0
  IPC::Open3: 0
  Moose: 0
  Moose::Autobox: 0
  Moose::Role: 0
  MooseX::Has::Sugar: 0
  MooseX::Types::Moose: 0
  String::Formatter: 0
  perl: 5.010
resources:
  X_mailing_list: http://www.listbox.com/subscribe/?list_id=139292
  bugtracker: http://rt.cpan.org/Public/Dist/Display.html?Name=Dist-Zilla-Plugin-Git
  homepage: http://search.cpan.org/dist/Dist-Zilla-Plugin-Git/
  repository: http://github.com/jquelin/dist-zilla-plugin-git
version: 1.102010
x_Dist_Zilla:
  plugins:
    -
      class: Dist::Zilla::Plugin::MetaResources
      name: MetaResources
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::AutoVersion
      name: '@JQUELIN/AutoVersion'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@JQUELIN/GatherDir'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::CompileTests
      name: '@JQUELIN/CompileTests'
      version: 1.101800
    -
      class: Dist::Zilla::Plugin::CriticTests
      name: '@JQUELIN/CriticTests'
      version: 1.100140
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@JQUELIN/HasVersionTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::KwaliteeTests
      name: '@JQUELIN/KwaliteeTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::MetaTests
      name: '@JQUELIN/MetaTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MinimumVersionTests
      name: '@JQUELIN/MinimumVersionTests'
      version: 1.101421
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@JQUELIN/PodCoverageTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@JQUELIN/PodSyntaxTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PortabilityTests
      name: '@JQUELIN/PortabilityTests'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::ReportVersions
      name: '@JQUELIN/ReportVersions'
      version: 1.101700
    -
      class: Dist::Zilla::Plugin::UnusedVarsTests
      name: '@JQUELIN/UnusedVarsTests'
      version: 1.100860
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@JQUELIN/PruneCruft'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ManifestSkip
      name: '@JQUELIN/ManifestSkip'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::AutoPrereq
      name: '@JQUELIN/AutoPrereq'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ExtraTests
      name: '@JQUELIN/ExtraTests'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@JQUELIN/NextRelease'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PkgVersion
      name: '@JQUELIN/PkgVersion'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::PodWeaver
      name: '@JQUELIN/PodWeaver'
      version: 3.101640
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@JQUELIN/Prepender'
      version: 1.101590
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@JQUELIN/ExecDir'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@JQUELIN/ShareDir'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Bugtracker
      name: '@JQUELIN/Bugtracker'
      version: 1.101490
    -
      class: Dist::Zilla::Plugin::Homepage
      name: '@JQUELIN/Homepage'
      version: 1.101420
    -
      class: Dist::Zilla::Plugin::Repository
      name: '@JQUELIN/Repository'
      version: 0.13
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      name: '@JQUELIN/MetaProvides::Package'
      version: 1.10001919
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@JQUELIN/MetaConfig'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::License
      name: '@JQUELIN/License'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@JQUELIN/MetaYAML'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::ModuleBuild
      name: '@JQUELIN/ModuleBuild'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Readme
      name: '@JQUELIN/Readme'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@JQUELIN/Manifest'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::CheckChangeLog
      name: '@JQUELIN/CheckChangeLog'
      version: 0.01
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@JQUELIN/UploadToCPAN'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@JQUELIN/Git/Check'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@JQUELIN/Git/Commit'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@JQUELIN/Git/Tag'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@JQUELIN/Git/Push'
      version: 1.100970
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: 4.101900
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: 4.101900
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: 0
    version: 4.101900
